// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart2: typeof import('./src/components/chartComponents/chart2.vue')['default']
    CodeMirror: typeof import('./src/components/codeMirror/codeMirror.vue')['default']
    FooterCom: typeof import('./src/components/footerCom.vue')['default']
    HeaderCom: typeof import('./src/components/headerCom.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    LineCahrt: typeof import('./src/components/chartComponents/lineCahrt.vue')['default']
    NaPagination: typeof import('./src/components/pagination/naPagination.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/fileUploadCom/upload.vue')['default']
  }
}

export {}
