// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart2: typeof import('./src/components/chartComponents/chart2.vue')['default']
    CodeMirror: typeof import('./src/components/codeMirror/codeMirror.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    IndexAddEditModal: typeof import('./src/components/indexAddEditModal.vue')['default']
    IndexTable: typeof import('./src/components/indexTable.vue')['default']
    LineCahrt: typeof import('./src/components/chartComponents/lineCahrt.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Pagination: typeof import('./src/components/pagination/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/fileUploadCom/upload.vue')['default']
    WEditor: typeof import('./src/components/wangEditor/wEditor.vue')['default']
  }
}

export {}
